export const MY_COGS_FILTER_COLLECTION = "MY_COGS_FILTER_COLLECTION";
export const MY_COGS_ADD_COLLECTION = "MY_COGS_ADD_COLLECTION";
export const MY_COGS_ADD_LABEL = "MY_COGS_ADD_LABEL";
export const MY_COGS_ADD_RELEASE = "MY_COGS_ADD_RELEASE";
